name: Santiago Ortiz de Marco
favicon: null
layout_spectrum: 0.15733152395114303
typography_spectrum: 0.6899398299865425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.06435430888086557
  lightness: 0.992565528023988
  saturation: 0.9519002877641469
  rhythmicContrast: 0.14512880775146186
purpose: []
